package action;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.util.Base64;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.control.TextArea;

public class EncryptorController {
	@FXML
	private Button encryptBtn;
	@FXML
	private TextField fieldInput;
	@FXML
	private TextArea encryptedTxt;

	// Event Listener on Button[#encryptBtn].onAction
	@FXML
	public void btnClick(ActionEvent event) {
		// TODO Autogenerated
		String input = fieldInput.getText();
		if (!(input.equals("") || input.equals(" "))) {
			try {
				String encrypted = encrypt(input);
				encryptedTxt.clear();
				encryptedTxt.appendText(encrypted);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
	
	private String encrypt(String data) throws Exception {
		byte[] encodedVal = data.getBytes();
		String encoded = Base64.getEncoder().encodeToString(encodedVal);
		//System.out.println("encoded: " + encoded);
		return encoded;
	}
}
